version: "3.8"

services:
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    depends_on:
      - db
    ports:
      - "6432:6432"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: medbrain
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 50
      RESERVE_POOL_SIZE: 10
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt

volumes:
  db_data:
