[databases]
# Use your Neon connection details here.
# Replace placeholders with your Neon host, user, dbname, and password.
postgres = host=ep-wispy-band-a5hu66v3-pooler.us-east-2.aws.neon.tech port=5432 dbname=medbrain_prod user=neondb_owner password=npg_FbrWQUsR65nP sslmode=require

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = session
server_reset_query = DISCARD ALL
max_client_conn = 100
default_pool_size = 20
log_connections = 1
log_disconnections = 1
